DROP TABLE IF EXISTS event_category CASCADE;
DROP TABLE IF EXISTS event_users CASCADE;
DROP TABLE IF EXISTS events_bids CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bids CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(250) NOT NULL,
    lastname VARCHAR(250) NOT NULL,
    birthdate DATE NOT NULL,
    date_of_registration DATE,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50)  NOT NULL,

    CONSTRAINT chk_user_status CHECK (status IN ('ACTIVE', 'BANNED', 'DELETED', 'PENDING'))
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,

    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_of_event VARCHAR(255) NOT NULL,
    status VARCHAR(50)  NOT NULL,
    date_start DATE NOT NULL,
    date_end DATE NOT NULL,
    total_places INTEGER NOT NULL,
    free_places INTEGER NOT NULL,
    user_id BIGINT,

    CONSTRAINT fk_events_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_event_status CHECK (status IN ('NEW', 'WAIT_FOR_PUBLISH', 'PUBLISHED', 'CANCELED')),
    CONSTRAINT chk_event_dates CHECK (date_end >= date_start),
    CONSTRAINT chk_places_count CHECK (total_places >= 0 AND free_places >= 0 AND free_places <= total_places)
);

CREATE TABLE bids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    count_of_places INTEGER NOT NULL,
    user_id BIGINT,
    event_id BIGINT,

    CONSTRAINT fk_bids_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_bids_to_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT chk_bid_places CHECK (count_of_places > 0)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    user_id BIGINT,

    CONSTRAINT fk_comments_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE event_category (
    event_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,

    CONSTRAINT pk_event_category PRIMARY KEY (event_id, category_id),
    CONSTRAINT fk_ec_to_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_ec_to_categories FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE TABLE event_users (
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT pk_event_users PRIMARY KEY (event_id, user_id),
    CONSTRAINT fk_eu_to_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_eu_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE events_bids (
    event_id BIGINT NOT NULL,
    bid_id BIGINT NOT NULL,

    CONSTRAINT pk_events_bids PRIMARY KEY (event_id, bid_id),
    CONSTRAINT fk_eb_to_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_eb_to_bids FOREIGN KEY (bid_id) REFERENCES bids (id) ON DELETE CASCADE
);